### ISSUE TITLE
Workarounds for jqr bugs?

### ISSUE THREAD

**Issue by mgirlich** [mgirlich/jsontools#12]
Known jqr bugs:
* [ ] `jqr::jq(c("1", "2"))`: returns 12 (see https://github.com/ropensci/jqr/issues/79)
* [ ] `jqr::jq(NA_character_)`: errors (see https://github.com/ropensci/jqr/issues/78)
* [ ] `jqr::jq(c('{"a": 1}', '2'), ".a")`: suppresses error and doesn't return anything for 2nd argument (see https://github.com/ropensci/jqr/issues/80)
